[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar backend/build/libs/*.jar"
healthcheckPath = "/api/id-validation/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"

[services.variables]
SPRING_DATASOURCE_URL = "jdbc:postgresql://postgres:5432/railway"
SPRING_DATASOURCE_USERNAME = "postgres"
SPRING_DATA_REDIS_HOST = "redis"
SPRING_DATA_REDIS_PORT = "6379"
